clear all;
f = imread('Einstein.tif');
hf = imhist(f);
g = histeq(f);
hg = imhist(g);
figure(1);
subplot(2, 2, 1); imshow(f);
subplot(2, 2, 2); plot(hf);
subplot(2, 2, 3); imshow(g);
subplot(2, 2, 4); plot(hg);
